---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.4
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[ak-openerp-base]
  attributes:
    openerp:
      group_unix: erp_group
      
