driver_plugin: docker
driver_config:
  require_chef_omnibus: false
  customize:
    memory: 1024

platforms:
  - name: ubuntu-12.04
    driver_config:
      image: okapies/chef-solo
      platform: ubuntu
    run_list:
    - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[ak-odoo-chef-base]
    attributes:

provision_command:
  - apt-get install telnet
